### PR TITLE
Convert CLJX to CLJC

### PR DESCRIPTION
**Pull request by plexus**
It's a pretty straightforward change. I also updated some dependencies.

### CODE REVIEW

**Comment by jaycfields** [comment]
Can someone, @imikushin or @ptaoussanis maybe, check the cljs side of this? I've still yet to write a cljs hello world so I can't really verify appropriately. I'll check out the clj side though, and if that's good, I'm fine to merge.

**Comment by jaycfields** [comment]
I'm going to merge to make this easy to verify, and we'll do a release when I get the lgtm on cljs

**Comment by ptaoussanis** [comment]
@jaycfields Hi Jay, my apologies - won't be able to help you confirm. Don't have any Cljs projects setup for Expectations atm.

**Comment by jaycfields** [comment]
no worries @ptaoussanis, given the support to this point, I don't blame you. :)

**Comment by ptaoussanis** [comment]
No problem, might try again when I have some free time - would definitely like to see it working.

Good luck!

**Comment by jaycfields** [comment]
@plexus when I run `lein expectations` I can't seem to get it to pick up the success examples. 

I opened things up in emacs and I am able to run there using `expectations-mode`, and I see a failing test:

```
failure in (success_examples.cljc:244) : success.success-examples
           expected: :a-rebound-val 
                was: nil
```

**Comment by plexus** [comment]
I'll have a look. Which version of `expectations-mode` are you using? I tried this one earlier, but it seems to no longer work with present-day cider.

https://github.com/gar3thjon3s/expectations-mode

**Comment by jaycfields** [comment]
I have no idea honestly, probably one that's a few years too old.

It's probably better for everyone if we get it working with "lein-expectations "0.0.8"" and ignore expectations-mode :)

**Comment by plexus** [comment]
I'm a bit out of my depth figuring out how the test suite is set up...

This is what I get when I run `lein expectations`

```
± lein expectations
WARNING: success.success-examples:175 modified #'success.success-examples-src/an-atom from "atom" to "atom"
WARNING: success.success-examples:182 modified #'success.success-examples-src/an-private-atom from "private-atom" to "private-atom"
WARNING: success.success-examples:189 modified #'success.success-examples-src/an-atom from "atom" to "atom"
WARNING: success.success-examples:196 modified #'success.success-examples-src/an-private-atom from "private-atom" to "private-atom"
yeah, you're done.

Ran 70 tests containing 70 assertions in 56 msecs
0 failures, 0 errors.
```

* I assumed those were all the tests. How many should I be seeing? 
* Is there a way to change the output format to see the names of all the tests that ran?
* Is there a wrapper that runs `failure-examples` and checks that they all fail, or does one verify manually that none of those pass?
* what's up with the JUnit stuff?

Sorry for the many questions! Any answers at all would be greatly appreciated!

**Comment by plexus** [comment]
`lein-expectations` seems to run fine, it picks up all tests in `success.success-examples` (59) and `success.nested.success-examples` (11).

The error indicates a missing `in-context` function which is defined in `success.expectations-options`, so it's probably that that namespace isn't being loaded by `expectations-mode`.

There are also tests in `test/expectations/expectations_expectations.clj` which are not being picked up, but they rely on a method that's been deleted for some time (`compare-args`), so I'm guessing they are vestigial?

**Comment by jaycfields** [comment]
I used to run things with `lein expectations success.*` and see everything passing, and then `lein expectations failure.*` and see a failure or error for each assertion. I got the failures running with https://github.com/jaycfields/expectations/commit/e2b1623d74a982d0b7085dd71dc6862bcda518e5

I'm not sure why I'm not seeing the successes. I'll try a fresh checkout.

output all namespaces: I think that's possible, but I honestly don't remember how and can't find the PR with the example.

ignore junit, if anyone ever reports it as broken I'm going to delete it. Until that happens I'm just assuming all is well. :)

**Comment by jaycfields** [comment]
> There are also tests in test/expectations/expectations_expectations.clj which are not being picked up, but they rely on a method that's been deleted for some time (compare-args), so I'm guessing they are vestigial?

Correct. I just pushed a commit that at least gets everything green. (for that ns)

**Comment by jaycfields** [comment]
I just checked out a fresh copy and I'm still not seeing the success tests running

```
Ran 45 tests containing 45 assertions in 300 msecs
43 failures, 2 errors.
```

Those are all the failures. I'm trying to think of an environment change that I might have, but nothing comes to mind.

**Comment by plexus** [comment]
@jaycfields is this with `expectations-mode` or how are you running the tests? Could you try the aliases in #72?

**Comment by jaycfields** [comment]
I'm ignoring expectations-mode, I'm just running using `lein expectations`. At least I was, I just tried `lein test` and I get
```
lmp-jfields02:expectations jfields$ lein test

Ran 6 tests containing 6 assertions in 24 msecs
0 failures, 0 errors.
```
Even my fresh checkout gives that..

**Comment by jaycfields** [comment]
```
$ lein --version
Leiningen 2.5.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by plexus** [comment]
It seems in your case it only ever picks up one namespace. No idea what could be causing that.

I did a `rm -rf ~/.m2` and cleared out `~/.lein/profiles.clj`, and it still runs ok...

I did have a type in the invocation of `test-fail`, I just repushed my branch.

```
$ lein test 
<warnings>

Ran 76 tests containing 76 assertions in 75 msecs
0 failures, 0 errors.
```

```
$ lein test-fail
<failures>

Ran 45 tests containing 45 assertions in 339 msecs
43 failures, 2 errors.
```

```
$ lein -v
Leiningen 2.6.1 on Java 1.8.0_77 Java HotSpot(TM) 64-Bit Server VM
```

Maybe a third opinion would be good? Could someone try to run this and report back?

```
git clone -b run-test-alias git@github.com:plexus/expectations.git 
cd expectations
lein test-fail
lein test
```

**Comment by jaycfields** [comment]
I have a second laptop here and it looks good there, so don't worry about it anymore.

Can you send me a PR for the typo fix?

**Pull request merged**
